module.exports = async ({evaluate,record,assert}) => {
  const parsed=await evaluate(`(()=>{const html=jobs=>'<script>var mArg = ""; mArg = '+JSON.stringify({attachments:jobs,note:'a brace { inside a quoted string }'})+';window.unsafeHtmlRan=1;<\/script>';const completed=flowFixture.parseCxCardCompletion(html([{jobid:'job1',isPassed:true},{jobid:'job2',isPassed:true}]));const mixed=flowFixture.parseCxCardCompletion(html([{jobid:'job1',isPassed:true},{jobid:'job2',isPassed:false},{isPassed:true}]));const malformed=flowFixture.parseCxCardCompletion('<script>mArg={attachments:[{jobid:"job1",isPassed:true}]};<\/script>');const empty=flowFixture.parseCxCardCompletion(html([]));const loose=flowFixture.parseCxCardCompletion(html([{jobid:'job1',isPassed:'true'}]));return {completed,mixed,malformed,empty,loose,executed:!!window.unsafeHtmlRan};})()`);
  assert.deepEqual(parsed,{completed:{total:2,unfinished:0},mixed:{total:2,unfinished:1},malformed:null,empty:null,loose:{total:1,unfinished:1},executed:false});
  record('Official card parser handles the real empty-then-JSON assignment, quoted braces, multiple jobs and strict boolean status without executing HTML');
  const official=await evaluate(`(async()=>{const src='https://fixture.example/mooc-ans/knowledge/cards?courseid=1&clazzid=2&knowledgeid=3&num=0';let request;const page={src,iframe:{src,contentDocument:{readyState:'complete',URL:src},contentWindow:{fetch:async(url,options)=>{request={samePage:url===src,credentials:options.credentials,cache:options.cache};return {ok:true,url:src,text:async()=>'<script>var mArg="";mArg={"attachments":[{"jobid":"job1","isPassed":true}]};<\/script>'};}}}};const result=await flowFixture.readCxCardCompletion(page,{signal:new AbortController().signal,isCurrent:()=>true});return {result,request};})()`);
  assert.deepEqual(official,{result:{state:{total:1,unfinished:0},error:''},request:{samePage:true,credentials:'include',cache:'no-store'}});
  record('A stale visual marker can be checked with a read-only authenticated request for the same official card');
  const refused=await evaluate(`(async()=>{const src='https://fixture.example/mooc-ans/knowledge/cards?courseid=1&clazzid=2&knowledgeid=3&num=0';const context={signal:new AbortController().signal,isCurrent:()=>true};const outcomes=[];for(const url of ['https://fixture.example/login',src.replace('knowledgeid=3','knowledgeid=4')]){const page={src,iframe:{src,contentDocument:{readyState:'complete',URL:src},contentWindow:{fetch:async()=>({ok:true,url,text:async()=>'<script>mArg={"attachments":[{"jobid":"job1","isPassed":true}]};<\/script>'})}}};outcomes.push((await flowFixture.readCxCardCompletion(page,context)).state);}return outcomes;})()`);
  assert.deepEqual(refused,[null,null]);
  record('Login redirects and another chapter response cannot confirm completion for the current card');
  const cancelled=await evaluate(`(async()=>{const src='https://fixture.example/mooc-ans/knowledge/cards?courseid=1&clazzid=2&knowledgeid=3&num=0';let current=true;const page={src,iframe:{src,contentDocument:{readyState:'complete',URL:src},contentWindow:{fetch:async()=>{current=false;return {ok:true,url:src,text:async()=>'<script>mArg={"attachments":[{"jobid":"job1","isPassed":true}]};<\/script>'};}}}};return await flowFixture.readCxCardCompletion(page,{signal:new AbortController().signal,isCurrent:()=>current});})()`);
  assert.deepEqual(cancelled,{state:null,error:''});
  record('A chapter change during the official request discards the stale completion response');
  const timeout=await evaluate(`(async()=>{const src='https://fixture.example/mooc-ans/knowledge/cards?courseid=1&clazzid=2&knowledgeid=3&num=0';const page={src,iframe:{src,contentDocument:{readyState:'complete',URL:src},contentWindow:{fetch:(_url,options)=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true}))}}};return await flowFixture.readCxCardCompletion(page,{signal:new AbortController().signal,isCurrent:()=>true},10);})()`);
  assert.equal(timeout.state,null);assert.match(timeout.error,/超时/);
  record('Official status lookup has a bounded timeout and cannot turn a failed request into completion');
  assert.deepEqual(await evaluate('window.fixtureErrors'),[]);
};
