module.exports = async ({evaluate,record,assert}) => {
  const frameOrder=await evaluate(`(()=>{const d=document.implementation.createHTMLDocument();d.body.innerHTML='<iframe src="about:blank"></iframe><iframe id="iframe" src="/mooc-ans/knowledge/cards"></iframe>';return flowFixture.getCxChapterFrame(d).id;})()`);
  assert.equal(frameOrder,'iframe');
  record('Regression: an editor iframe before the course frame does not change the active chapter');
  const navigationGate=await evaluate(`(()=>{const src='https://fixture.example/mooc-ans/knowledge/cards?courseid=1&clazzid=2&knowledgeid=3&num=0';return [flowFixture.isCxChapterFrameReady({src,contentDocument:{readyState:'complete',URL:src.replace('num=0','num=1')}}),flowFixture.isCxChapterFrameReady({src,contentDocument:{readyState:'complete',URL:src}}),flowFixture.isCxChapterFrameReady({src,contentDocument:{readyState:'loading',URL:src}})];})()`);
  assert.deepEqual(navigationGate,[false,true,false]);
  record('Chapter navigation cannot process the previous card document while a new card is loading');
  const rates=await evaluate('[10,2,1.5,1].map(flowFixture.getCxSaferRate)');
  assert.deepEqual(rates,[2,1,1,null]);
  record('Uncredited high-speed playback can lower to 2x and then 1x, with no further rate fallback at 1x');
  const missingFrame=await evaluate(`(()=>{const d=document.implementation.createHTMLDocument();d.body.innerHTML='<iframe src="about:blank"></iframe>';return flowFixture.getCxChapterFrame(d)===null;})()`);
  assert.equal(missingFrame,true);
  record('A missing course frame cannot process an unrelated editor document');
  const blankFrames=await evaluate(`(async()=>{const root=document.createElement('div');root.innerHTML='<iframe></iframe><iframe src="about:blank"></iframe><iframe src="javascript:void(0)"></iframe>';document.body.append(root);const frames=await flowFixture.collectCxTaskFrames(root,{isCurrent:()=>true,signal:new AbortController().signal});root.remove();return frames.length;})()`);
  assert.equal(blankFrames,0);
  record('Regression: video player blank/editor frames cannot stall task processing');
  const nativeNext=await evaluate(`(()=>{const root=document.createElement('div');root.innerHTML='<a class="nextChapter" style="display:none">隐藏下一节</a><div id="prevNextFocusNext">下一节</div>';document.body.append(root);let wrong=0,right=0;root.firstChild.onclick=()=>wrong++;root.lastChild.onclick=()=>right++;const clicked=flowFixture.clickCxNextChapter(root);root.lastChild.style.display='none';const hidden=flowFixture.clickCxNextChapter(root);root.remove();return {clicked,hidden,right,wrong};})()`);
  assert.deepEqual(nativeNext,{clicked:true,hidden:false,right:1,wrong:0});
  record('Regression: progression clicks the visible native next button once, never the hidden modal link');
  const cards=await evaluate(`(()=>{const root=document.createElement('ul');root.innerHTML='<li id="dct1" class="active">视频</li><li id="dct2">章节测验</li>';document.body.append(root);const completed=new Set();const first=flowFixture.getCxNextCard(root,completed)?.id;root.firstChild.className='';root.lastChild.className='active';const last=flowFixture.getCxNextCard(root,completed);root.remove();return {first,last,completed:Array.from(completed)};})()`);
  assert.deepEqual(cards,{first:'dct2',last:null,completed:['dct1','dct2']});
  record('The chapter quiz card is processed before advancing to the next chapter');
  const status=await evaluate(`(()=>{const root=document.createElement('div');root.innerHTML='<div><div class="ans-job-icon" aria-label="任务点未完成"></div><iframe></iframe></div>';const before=flowFixture.getCxCardTasks(root);root.firstChild.className='ans-job-finished';return {before,after:flowFixture.getCxCardTasks(root)};})()`);
  assert.deepEqual(status,{before:{total:1,unfinished:1},after:{total:1,unfinished:0}});
  record('Playback ending alone is insufficient; the platform completion marker is required');
  const waits=await evaluate(`(async()=>{const c=new AbortController(),context={signal:c.signal,isCurrent:()=>true};let done=false;setTimeout(()=>done=true,20);const confirmed=await flowFixture.waitForCxCondition(()=>done,context,800);const timeout=await flowFixture.waitForCxCondition(()=>false,context,20);const waiting=flowFixture.waitForCxCondition(()=>false,context,800);c.abort();return {confirmed,timeout,aborted:await waiting};})()`);
  assert.deepEqual(waits,{confirmed:true,timeout:false,aborted:false});
  record('Platform status waits handle delayed confirmation, timeout and chapter cancellation');
  const topPopup=await evaluate(`(async()=>{const c=new AbortController();let submitted=0,popups=0;const original=()=>popups++;const host={workPop:original};const work={top:host,document,btnBlueSubmit:()=>setTimeout(()=>host.workPop('确认提交？','提交','取消',()=>submitted++),20)};const result=await flowFixture.submitCxChapterWork(work,{signal:c.signal,isCurrent:()=>true},800);return {result,submitted,popups,restored:host.workPop===original};})()`);
  assert.deepEqual(topPopup,{result:true,submitted:1,popups:0,restored:true});
  record('Regression: the fully-answered parent-window confirmation submits once and restores the native dialog handler');
  const extraPopup=await evaluate(`(async()=>{let submitted=0,popups=0;const original=()=>popups++;const host={workPop:original};const work={top:host,document,btnBlueSubmit:()=>setTimeout(()=>host.workPop('您还有未做完的判断题，确认提交吗？','提交','取消',()=>submitted++),20)};let error='';try{await flowFixture.submitCxChapterWork(work,{signal:new AbortController().signal,isCurrent:()=>true},800)}catch(e){error=e.message}return {submitted,popups,restored:host.workPop===original,error};})()`);
  assert.equal(extraPopup.submitted,0);assert.equal(extraPopup.popups,1);assert.equal(extraPopup.restored,true);assert.match(extraPopup.error,/额外验证/);
  record('Incomplete-answer or extra-verification prompts remain native and cannot be auto-confirmed');
  const cancelPopup=await evaluate(`(async()=>{const c=new AbortController();const original=()=>{};const host={workPop:original},work={top:host,document,btnBlueSubmit:()=>{}};const p=flowFixture.submitCxChapterWork(work,{signal:c.signal,isCurrent:()=>!c.signal.aborted},800);c.abort();return {result:await p,restored:host.workPop===original};})()`);
  assert.deepEqual(cancelPopup,{result:false,restored:true});
  record('Chapter cancellation immediately restores temporary submit hooks without submitting');
  const popup=await evaluate(`(async()=>{const root=document.createElement('div');root.className='ans-videoquiz';root.innerHTML='<div class="tkItem_title">只有体力劳动属于劳动。</div><li class="ans-videoquiz-opt"><label><input type="radio" name="ans-videoquiz-opt">A、对</label></li><li class="ans-videoquiz-opt"><label><input type="radio" name="ans-videoquiz-opt">B、错</label></li><a id="videoquiz-submit">提交</a>';document.body.append(root);const controller=new AbortController();let enabled=false,calls=0,submits=0,released=0;root.querySelector('#videoquiz-submit').onclick=()=>{submits++;root.remove();};const watcher=flowFixture.watchVideoQuiz({document,signal:controller.signal,isCurrent:()=>true,isEnabled:()=>enabled,delayMs:()=>0,search:async()=>{calls++;return {success:true,data:{items:[{answer:{values:['错']}}]}}},similarityThreshold:()=>85,onRelease:()=>released++,log:()=>{}});const activeBefore=watcher.hasActiveQuiz();await new Promise(r=>setTimeout(r,600));const whileDisabled=calls;enabled=true;await new Promise(r=>setTimeout(r,2100));const after={calls,submits,released,active:watcher.hasActiveQuiz()};watcher.dispose();controller.abort();root.remove();return {activeBefore,whileDisabled,...after};})()`);
  assert.deepEqual(popup,{activeBefore:true,whileDisabled:0,calls:1,submits:1,released:1,active:false});
  record('An already-open replay quiz resumes after AI is enabled and submits exactly once');
  const cache=await evaluate(`(async()=>{aiFixture.clearCache();const q={type:'0',title:'刷新后的同题缓存',optionsText:['甲','乙'],searchText:{stem:'刷新后的同题缓存',options:['甲','乙']}};aiFixture.network.responses.push(...[0,0].map(index=>({payload:aiFixture.completion({option_indices:[index]})})));const first=await aiFixture.getAnswer(q,{skipDelay:true});aiVoteCache.clear();const n=aiFixture.network.requests.length;const second=await aiFixture.getAnswer(q,{skipDelay:true});const stored=_GM_getValue('deepseek-answer-cache-v1');const result={first:first.success,second:second.success,newRequests:aiFixture.network.requests.length-n,stored:stored.length,noKey:!JSON.stringify(stored).includes('sk-fixture-only')};aiFixture.clearCache();return result;})()`);
  assert.deepEqual(cache,{first:true,second:true,newRequests:0,stored:1,noKey:true});
  record('Winning votes survive page refresh for 24 hours without another request or a stored credential');
  assert.deepEqual(await evaluate('window.fixtureErrors'),[]);
};
