module.exports=async({evaluate,record,assert})=>{
  const reloaded=await evaluate(`(async()=>{const {video,state}=makeRecoveryVideo();state.paused=true;let ready=0;Object.defineProperty(video,'readyState',{get:()=>ready});video.play=async()=>{state.calls++;if(state.calls===1)throw new DOMException('New resource load','AbortError');state.paused=false;};const controller=new AbortController();const options={signal:controller.signal,isCurrent:()=>true};const first=flowFixture.ensureMediaPlaying(video,options);const second=flowFixture.ensureMediaPlaying(video,options);setTimeout(()=>{ready=3;video.dispatchEvent(new Event('canplay'));},20);return {sameRequest:first===second,first:await first,second:await second,calls:state.calls,paused:state.paused};})()`);
  assert.deepEqual(reloaded,{sameRequest:true,first:true,second:true,calls:2,paused:false});
  record('Regression: an AbortError during resource reload waits for canplay and resumes; concurrent triggers share one request');
  const cancelled=await evaluate(`(async()=>{const {video,state}=makeRecoveryVideo();state.paused=true;Object.defineProperty(video,'readyState',{get:()=>0});video.play=async()=>{state.calls++;throw new DOMException('Reload','AbortError');};const controller=new AbortController();const work=flowFixture.ensureMediaPlaying(video,{signal:controller.signal,isCurrent:()=>true});setTimeout(()=>controller.abort(),10);return {playing:await work,calls:state.calls};})()`);
  assert.deepEqual(cancelled,{playing:false,calls:1});
  record('Navigation cancels the readiness wait and prevents another play attempt');
  const popup=await evaluate(`(async()=>{const {video,state}=makeRecoveryVideo();state.paused=true;let ready=0,blocked=false;Object.defineProperty(video,'readyState',{get:()=>ready});video.play=async()=>{state.calls++;throw new DOMException('Reload','AbortError');};const work=flowFixture.ensureMediaPlaying(video,{signal:new AbortController().signal,isCurrent:()=>true,isBlocked:()=>blocked});setTimeout(()=>{blocked=true;ready=3;video.dispatchEvent(new Event('canplay'));},10);return {playing:await work,calls:state.calls};})()`);
  assert.deepEqual(popup,{playing:false,calls:1});
  record('A video quiz that appears while waiting for a reload prevents automatic playback');
  const bounded=await evaluate(`(async()=>{const {video,state}=makeRecoveryVideo();state.paused=true;Object.defineProperty(video,'readyState',{get:()=>3});video.play=async()=>{state.calls++;throw new DOMException('Repeated reload','AbortError');};let message;try{await flowFixture.ensureMediaPlaying(video,{signal:new AbortController().signal,isCurrent:()=>true});}catch(error){message=error.message;}return {calls:state.calls,message};})()`);
  assert.equal(bounded.calls,3);assert.match(bounded.message,/反复重载/);
  record('Repeated resource reload interruption stops with a clear error after three attempts');
  const failures=await evaluate(`(async()=>{const outcomes=[];for(const kind of ['NotAllowedError','timeout']){const {video,state}=makeRecoveryVideo();state.paused=true;Object.defineProperty(video,'readyState',{get:()=>0});video.play=async()=>{state.calls++;throw new DOMException('Failure',kind==='timeout'?'AbortError':kind);};let message,name;try{await flowFixture.ensureMediaPlaying(video,{signal:new AbortController().signal,isCurrent:()=>true,timeoutMs:10});}catch(error){message=error.message;name=error.name;}outcomes.push({calls:state.calls,message,name});}return outcomes;})()`);
  assert.equal(failures[0].calls,1);assert.equal(failures[0].name,'NotAllowedError');assert.equal(failures[1].calls,1);assert.match(failures[1].message,/加载超时/);
  record('Autoplay permission errors are not retried, and a missing readiness event produces a bounded load timeout');
  assert.deepEqual(await evaluate('window.fixtureErrors'),[]);
};
