const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const zlib=require('node:zlib');
const {spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const scriptName='chaoxing-deepseek-helper.user.js';
const source=fs.readFileSync(path.join(root,scriptName),'utf8');
const version=source.match(/^\/\/ @version\s+(\S+)/m)?.[1];
if(!version)throw new Error('Missing userscript version');
const end=source.indexOf('// ==/UserScript==')+'// ==/UserScript=='.length;
if(end<'// ==/UserScript=='.length)throw new Error('Missing metadata end');
fs.writeFileSync(path.join(root,'chaoxing-deepseek-helper.meta.js'),source.slice(0,end)+'\n');
const checked=spawnSync(process.execPath,[path.join(__dirname,'check.cjs')],{stdio:'inherit'});
if(checked.status!==0)process.exit(checked.status||1);
const names=[scriptName,'chaoxing-deepseek-helper.meta.js','README.md','LICENSE','NOTICE.md','CHANGELOG.md','VERIFICATION.md'];
const entries=names.map(name=>({name,bytes:fs.readFileSync(path.join(root,name))}));
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const checksums=entries.map(e=>`${sha(e.bytes)}  ${e.name}`).join('\n')+'\n';
entries.push({name:'SHA256SUMS',bytes:Buffer.from(checksums)});
const crcTable=Array.from({length:256},(_,value)=>{for(let i=0;i<8;i++)value=(value&1)?0xedb88320^(value>>>1):value>>>1;return value>>>0;});
const crc32=bytes=>{let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;};
const chunks=[],central=[];
let offset=0;
const now=new Date();
const dosDate=((Math.max(1980,now.getUTCFullYear())-1980)<<9)|((now.getUTCMonth()+1)<<5)|now.getUTCDate();
const dosTime=(now.getUTCHours()<<11)|(now.getUTCMinutes()<<5)|Math.floor(now.getUTCSeconds()/2);
for(const entry of entries){
  const name=Buffer.from(entry.name),data=zlib.deflateRawSync(entry.bytes),crc=crc32(entry.bytes);
  const header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50,0);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(8,8);header.writeUInt16LE(dosTime,10);header.writeUInt16LE(dosDate,12);header.writeUInt32LE(crc,14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(entry.bytes.length,22);header.writeUInt16LE(name.length,26);
  const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50,0);directory.writeUInt16LE(20,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt16LE(8,10);directory.writeUInt16LE(dosTime,12);directory.writeUInt16LE(dosDate,14);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(data.length,20);directory.writeUInt32LE(entry.bytes.length,24);directory.writeUInt16LE(name.length,28);directory.writeUInt32LE(offset,42);
  chunks.push(header,name,data);central.push(directory,name);offset+=header.length+name.length+data.length;
}
const centralBytes=Buffer.concat(central),footer=Buffer.alloc(22);footer.writeUInt32LE(0x06054b50,0);footer.writeUInt16LE(entries.length,8);footer.writeUInt16LE(entries.length,10);footer.writeUInt32LE(centralBytes.length,12);footer.writeUInt32LE(offset,16);
const zip=Buffer.concat([...chunks,centralBytes,footer]);
const output=path.join(root,'.artifacts',`release-${version}-${Date.now()}`);fs.mkdirSync(output,{recursive:true});
for(const entry of entries)fs.writeFileSync(path.join(output,entry.name),entry.bytes);
const zipName=`chaoxing-deepseek-helper-v${version}.zip`;fs.writeFileSync(path.join(output,zipName),zip);
fs.writeFileSync(path.join(output,`${zipName}.sha256`),`${sha(zip)}  ${zipName}\n`);
const manifest={version,output,zip:zipName,zipSHA256:sha(zip),files:entries.map(entry=>({name:entry.name,sha256:sha(entry.bytes),bytes:entry.bytes.length}))};
fs.writeFileSync(path.join(root,'.artifacts','latest-package.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({version,zip:path.join(output,zipName),sha256:manifest.zipSHA256,entries:entries.length}));
